steps:

  # This steps clone the repository into GCP
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://PatrickVibild:holadontsteal1@github.com/PatrickVibild/frontend-admin']

  #This step creates a container and leave it on CloudBuilds repository.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: ['build', '-t', 'gcr.io/abiding-robot-255320/frontend-admin:$SHORT_SHA', '.']

  #Adds the container to Google container registry as an artefact
  - name: 'gcr.io/cloud-builders/docker'
    id: Container push
    args: ['push', 'gcr.io/abiding-robot-255320/frontend-admin:$SHORT_SHA']

  #Uses the container and replaces the existing one in Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Kubernetes deployment
    args: ['set', 'image', 'deployment/front-end-admin', 'frontend-admin-sha256=gcr.io/abiding-robot-255320/frontend-admin:$SHORT_SHA']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=scrapper-cluster'
